# Site
title:              Analisis y Visualizacion de Datos
bio:                'Rodrigo Crespillo y Juan Dias'
description:        "Analsis y Visualizacion de Datos"
locale:             en_US
baseurl: "/AnalisisyVisualizacion/" # the subpath of your site, e.g. /blog
url: "https://rodixxi.github.io" # the base hostname & protocol for your site

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   default

# Social
analytics-id:       "default"
twitter:            rodixxi
facebook:           rodixxi
instagram:          rodixxi
github:             rodixxi

# personal
location:           Córdoba, Córdoba
phone:              +54 9 0 3574 15 407371
email:              rodixxi@gmail.com

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
